global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "go-security-app"
    static_configs:
      - targets: ["localhost:8080"] # Update to your app's port

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["localhost:9093"]

rule_files:
  - "alerts.yml"

- alert: HighErrorRate
  expr: rate(http_requests_total[1m]) > 10
  for: 1m
  labels:
    severity: critical
  annotations:
    summary: "High error rate detected!"
